### PR TITLE
preparatory: update for breaking gcloud API change

### PR DESCRIPTION
**Pull request by zbjornson**
Not ready for merge!

This is in preparation for a breaking change coming soon:
https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1666

### CODE REVIEW

**Comment by Tapppi** [comment]
Should be ready with `v0.42` and `v0.43` both having being released.

**Comment by zbjornson** [comment]
@mlazarov finally updated and tested, this is ready to go from my end.

**Comment by mlazarov** [comment]
The code looks good but bumping the minor version will be better than patch?

**Comment by zbjornson** [comment]
The code change doesn't affect the API provided by this library or otherwise change any behavior, so I lean toward patch and not minor, but you're right that this is an ambiguity in the semver spec that has come up a lot (e.g. [a](https://github.com/mojombo/semver/issues/148), [b](http://stackoverflow.com/questions/23096170/should-major-semver-updates-cascade)). I think the most relevant responses from those thread point toward "patch", but I defer to your decision. :)

**Pull request merged**
